### PR TITLE
Grantee details position style

### PR DESCRIPTION
**Pull request by kbighorse**
## Description of change
Alignment and position improvements

## Issue(s)

* closes #0

## Checklist

To be completed by the submitter:

- [ ] Meets issue criteria
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

## To the Reviewer

This project is using [Conventional Comments](https://conventionalcomments.org/) to give structure
and context to PR comments. Please use these labels in your comments.

* **praise:**
* **nitpick:**
* **suggestion:**
* **issue:**
* **question:**
* **thought:**
* **chore:**

### CODE REVIEW

**Comment by kbighorse** [comment]
image

**Comment by kbighorse** [comment]
`usa-list--unstyled` did the heavy lifting

**Review by Sgtpluck — APPROVED** [review]
this change looks great. just wondering though -- have you checked the complaint detail view where `summary-body` and `summary-section` are used as classes? i'm wondering if there are tiny updates that need to be done there

**Comment by kbighorse** [comment]
@Sgtpluck no I haven't yet! stay tuned..

**Comment by kbighorse** [comment]
The only thing I would bring up is the [`ct-section-divider` class](https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/blob/main/app/assets/stylesheets/complaints.scss#L33) has bottom padding, so in these changes, there's now additional padding. It looks fine to my eye in complaints details, so I might hold off on removing it since that class is used elsewhere I didn't look at.

**Pull request merged**
