### PR TITLE
Grantee complaints list

### LINKED ISSUE #121: Grantee complaints list - M
User Story:
As a program specialist
I want to view the history of complaints about a grantee
So that I can understand the number, type, and resolution of complaints they have received

Acceptance:
Given that I am a Program Specialist
When I view the grantees details page
Then I see a list of complaints for that grantee

### PR DESCRIPTION
**Pull request by kbighorse**
## Issue(s)

* closes #121 

## Checklist

To be completed by the submitter:

- [ ] Meets issue criteria
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

## To the Reviewer

This project is using [Conventional Comments](https://conventionalcomments.org/) to give structure
and context to PR comments. Please use these labels in your comments.

* **praise:**
* **nitpick:**
* **suggestion:**
* **issue:**
* **question:**
* **thought:**
* **chore:**

### CODE REVIEW

**Review by Sgtpluck — DISMISSED** [review]
nice work! a few small suggestions, but also the styling of the component looks pretty off, so that should be fixed before this is mergable.

**Comment by rahearn** [comment]
For posterities sake, here's the updated CSS work:

Screen Shot 2021-10-29 at 4 24 14 PM

**Review by rahearn — APPROVED** [review]
🎉

**Comment by kbighorse** [comment]
thanks so much for the styling help @rahearn !

**Pull request merged**
