### PR TITLE
Add capybara and integration tests around the TTA activity report form

### LINKED ISSUE #154: Add integration tests (#96)
This task is part of #96.

We now have javascript interactivity, so we should add integration tests to ensure that the view is fully covered by tests.

Full User Story:
Given that I am a program specialist
When I add an AR ID to the complaints details
Then I can see that AR in the timeline

This task is scoped to:
- [ ] Adding integration tests

### PR DESCRIPTION
**Pull request by Sgtpluck**
## Description of change
Adding integration tests to the system

## Acceptance Criteria
The tests pass!

## How to test
GitHub Action is doing it for us.

## Issue(s)

* closes #154 

## Checklist

To be completed by the submitter:

- [ ] Meets issue criteria
- [ ] Code is meaningfully tested

## To the Reviewer

This project is using [Conventional Comments](https://conventionalcomments.org/) to give structure
and context to PR comments. Please use these labels in your comments.

* **praise:**
* **nitpick:**
* **suggestion:**
* **issue:**
* **question:**
* **thought:**
* **chore:**

### CODE REVIEW

**Comment by kbighorse** [comment]
👀

**Comment by kbighorse** [comment]
issue: tests initially fail with [errors](https://gist.github.com/kbighorse/ad42c45e7b04282912e033c77062a136)

there is some setup required to run integration tests:
[ ] install capybara
- `bundle install`
[ ] install `chromedriver` per https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver
- `brew install --cask chromedriver`
[ ] `chromedriver` must be allowed to run, or will fail to run, see: [error](https://stackoverflow.com/questions/60362018/macos-catalinav-10-15-3-error-chromedriver-cannot-be-opened-because-the-de)
- `xattr -d com.apple.quarantine $(which chromedriver)`

**Comment by kbighorse** [comment]
issue: it's very close, currently seeing these failures:
```
% bundle exec rake spec
/Users/kimballbighorse/.rvm/rubies/ruby-3.0.2/bin/ruby -I/Users/kimballbighorse/.rvm/gems/ruby-3.0.2@complaint-tracker/gems/rspec-core-3.10.1/lib:/Users/kimballbighorse/.rvm/gems/ruby-3.0.2@complaint-tracker/gems/rspec-support-3.10.2/lib /Users/kimballbighorse/.rvm/gems/ruby-3.0.2@complaint-tracker/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Capybara starting Puma...
* Version 5.5.0 , codename: Zawgyi
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:55228
...............................................................FFFF...........................................

Failures:

  1) Complaint relative_due_date_html due today returns the correct html string
     Failure/Error:
       expect(subject.relative_due_date_html).to eq(
         "<span class=\"ct-timeline__due-soon\">Due today (#{strftime})</span>"
       )
     
       expected: "<span class=\"ct-timeline__due-soon\">Due today (10/01/2021)</span>"
            got: "<span class=\"ct-timeline__overdue\">Overdue (Due 10/01/2021)</span>"
     
       (compared using ==)
     # ./spec/models/complaint_spec.rb:129:in `block (4 levels) in <main>'

  2) Complaint relative_due_date_html due in a single day returns the correct html string
     Failure/Error:
       expect(subject.relative_due_date_html).to eq(
         "<span class=\"ct-timeline__due-soon\">Due in 1 day (#{strftime})</span>"
       )
     
       expected: "<span class=\"ct-timeline__due-soon\">Due in 1 day (10/03/2021)</span>"
            got: "<span class=\"ct-timeline__due-soon\">Due in 2 days (10/03/2021)</span>"
     
       (compared using ==)
     # ./spec/models/complaint_spec.rb:141:in `block (4 levels) in <main>'

  3) Complaint relative_due_date_html due in a week returns the correct html string
     Failure/Error:
       expect(subject.relative_due_date_html).to eq(
         "<span class=\"ct-timeline__due-soon\">Due in 7 days (#{strftime})</span>"
       )
     
       expected: "<span class=\"ct-timeline__due-soon\">Due in 7 days (10/09/2021)</span>"
            got: "<span class=\"ct-timeline__due-soon\">Due in 8 days (10/09/2021)</span>"
     
       (compared using ==)
     # ./spec/models/complaint_spec.rb:153:in `block (4 levels) in <main>'

  4) Complaint relative_due_date_html due in a month returns the correct html string
     Failure/Error:
       expect(subject.relative_due_date_html).to eq(
         "<span>Due in 12 days (#{strftime})</span>"
       )
     
       expected: "<span>Due in 12 days (10/14/2021)</span>"
            got: "<span>Due in 13 days (10/14/2021)</span>"
     
       (compared using ==)
     # ./spec/models/complaint_spec.rb:165:in `block (4 levels) in <main>'

Finished in 8.84 seconds (files took 1.73 seconds to load)
110 examples, 4 failures

Failed examples:

rspec ./spec/models/complaint_spec.rb:126 # Complaint relative_due_date_html due today returns the correct html string
rspec ./spec/models/complaint_spec.rb:138 # Complaint relative_due_date_html due in a single day returns the correct html string
rspec ./spec/models/complaint_spec.rb:150 # Complaint relative_due_date_html due in a week returns the correct html string
rspec ./spec/models/complaint_spec.rb:162 # Complaint relative_due_date_html due in a month returns the correct html string

/Users/kimballbighorse/.rvm/rubies/ruby-3.0.2/bin/ruby -I/Users/kimballbighorse/.rvm/gems/ruby-3.0.2@complaint-tracker/gems/rspec-core-3.10.1/lib:/Users/kimballbighorse/.rvm/gems/ruby-3.0.2@complaint-tracker/gems/rspec-support-3.10.2/lib /Users/kimballbighorse/.rvm/gems/ruby-3.0.2@complaint-tracker/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

question: Did I miss a step somewhere?

**Comment by Sgtpluck** [comment]
@kbighorse hmm i am not sure why those tests are failing for you. they seem in my initial investigation to be unrelated to this change, which is scoped to just integration tests. i just reran on my machine and they're working for me locally, and the GitHub Action passed, so while that's an issue i don't think it's related to/should hold up this change once i add the documentation steps.

we should definitely figure out why those tests are failing. my gut instinct is they are a timezone/datetime issue, so we should probably debug and figure that out separately from this PR

**Review by rahearn — APPROVED** [review]
Love it

**Comment by kbighorse** [comment]
extracting out a time zone issue, but 👍 for this

**Pull request merged**
